version: '3.7'

services:
  web:
    restart: always
    build: ./django_server
    command: gunicorn city_logistics.wsgi:application --bind 0.0.0.0:8002 --access-logfile log/access.log --error-logfile log/error.log --workers 4
    network_mode: host
    env_file:
      - ./.env.prod
    volumes:
      - ./django_server:/django_server
  db:
    image: postgres:12.1
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    network_mode: host
  react:
    build: ./city_logistics_ui
    command: sh -c "yarn; yarn build"
    volumes:
      - ./city_logistics_ui:/city_logistics_ui
