version: '3.7'

services:
  web:
    build: ./django_server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_server/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  frontend:
      build: ./city_logistics_ui
      command: yarn start
      ports:
        - "3000:3000"
      volumes:
        - ./city_logistics_ui:/app/frontend
        - node-modules:/app/city_logistics_ui/node_modules

volumes:
  postgres_data:
  node-modules:
