# Generated by Django 3.1.2 on 2020-10-27 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holvi_orders', '0003_auto_20200604_0912'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(blank=True, max_length=64)),
                ('housenumber', models.CharField(blank=True, help_text='E.g. 3-5', max_length=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=8)),
                ('street_address', models.CharField(max_length=128, verbose_name='street address')),
                ('postal_code', models.CharField(max_length=16, verbose_name='postal code')),
                ('city', models.CharField(max_length=64, verbose_name='city')),
                ('country', models.CharField(max_length=64, verbose_name='country')),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('official', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=32, verbose_name='phone number')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourierCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_coordinator_for', to='fvh_courier.courier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('details', models.TextField(blank=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='in cm', null=True, verbose_name='height')),
                ('width', models.PositiveIntegerField(blank=True, help_text='in cm', null=True, verbose_name='width')),
                ('depth', models.PositiveIntegerField(blank=True, help_text='in cm', null=True, verbose_name='depth')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='in kg', max_digits=7, null=True, verbose_name='weight')),
                ('recipient', models.CharField(max_length=128, verbose_name='recipient')),
                ('recipient_phone', models.CharField(max_length=32, verbose_name='recipient phone number')),
                ('delivery_instructions', models.CharField(blank=True, max_length=256)),
                ('earliest_pickup_time', models.DateTimeField(verbose_name='earliest pickup time')),
                ('latest_pickup_time', models.DateTimeField(verbose_name='latest pickup time')),
                ('earliest_delivery_time', models.DateTimeField(verbose_name='earliest delivery time')),
                ('latest_delivery_time', models.DateTimeField(verbose_name='latest delivery time')),
                ('picked_up_time', models.DateTimeField(blank=True, null=True, verbose_name='picked up at')),
                ('delivered_time', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_packages', to='fvh_courier.courier', verbose_name='courier')),
                ('courier_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='fvh_courier.couriercompany')),
                ('deliver_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_packages', to='fvh_courier.address', verbose_name='destination')),
                ('pickup_at', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_packages', to='fvh_courier.address', verbose_name='pickup location')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['-earliest_pickup_time'],
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=32, verbose_name='phone number')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fvh_courier.address')),
                ('courier_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senders', to='fvh_courier.couriercompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequiredHolviProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('holvi_shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='required_product', to='holvi_orders.holviwebshop')),
            ],
        ),
        migrations.CreateModel(
            name='PackageSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.PositiveSmallIntegerField(choices=[(0, 'reservation'), (1, 'pickup'), (2, 'delivery'), (3, 'courier_notification'), (4, 'new_package')])),
                ('recipient_number', models.CharField(max_length=32)),
                ('twilio_sid', models.CharField(blank=True, max_length=64)),
                ('content', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='fvh_courier.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_packages', to='fvh_courier.sender', verbose_name='sender'),
        ),
        migrations.CreateModel(
            name='IgnoredHolviProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('holvi_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_products', to='holvi_orders.holviwebshop')),
            ],
        ),
        migrations.CreateModel(
            name='HolviPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='holvi_orders.holviorder')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fvh_courier.package')),
            ],
        ),
        migrations.AddField(
            model_name='courier',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='fvh_courier.couriercompany'),
        ),
        migrations.AddField(
            model_name='courier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
