# Generated by Django 3.1.2 on 2020-11-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fvh_courier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='couriercompany',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_coordinator_for', to='fvh_courier.courier'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='courier_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senders', to='fvh_courier.couriercompany'),
        ),
    ]
